### ISSUE TITLE
Эти переменные точно используются?

### ISSUE THREAD

**Issue by coursar** [protpolymer/deposit-calculator#3]
https://github.com/protpolymer/deposit-calculator/blob/20d39a58c11d85375419f7dd6e0ad7d85837be46/src/main/java/ru/itpark/DepositCalculatorService.java#L31-L32

Если нет, то удалить.

**Comment by protpolymer** [comment]
Переменные были добавлены на случай, если вдруг они понадобится в будущем. Так как в ходе данной задачи такие переменные вряд ли понадобятся, удалил их
